curl -i -b ".AspNetCore.Identity.Application=CfDJ8OY5n1bCHihOmEbI-Jaa3nLl1br3utRHcZosOxedh-Bo81ZbXvVzqOA-bHqDFn-KVWjR9Ix4GFbAc8bp75YIyLNcVA8k--T3bO7NjRIyZ51B73iW-zJwpgko8mvB_t8xGqa9C2blbzt__m-cnrn-JxkcWAz_UFy7mZ6VQo4ahcs1HkWFFBRMWWDzTJcH78D4a8QbpYA0Mto30yf9G7VvprMJQGLj78rssvz4kl7iTxLbPO8k0dV0u3E8ZpoC72uSk3xnV-SMrNcI6sd9aRvC9C-H6FQZRk3i9ijT3mZASkqp107JQMoAMVJmV-_REHXf2uMDEY_le2yCWzEBGJjPyT-sk_e0Tdhewbjl53tuSh0V69Np_0rOnkaV_Gm8ghhL7VHASTSAfXdYjyc0KDRqysToE1P_j2OrZFij2wkBd5sEqRIrbAsTO-c8WTxTzJkjbswj3QMC9qS02a0zNdHEJLhrha98jsRJEDw-buUl6JriVlwAK245fLGrPW9thG_QlwOCSatsyJL2texpXyWX-HmjDd4-2U2gvN7-jCHoyU07fqjNhkh-iYaAsbMbjNYkuYjP50tH6eJ8QUXDDDjSU8C_BISp2AmgNMQ4s-BHPUG8uJrPKFLwJwWZnZEncxkfvuQlTMpYsHo2uTSBslzVKRjy3_RKBjf_SkxyKvRSOEbZaizzNDOVhVVwwYzM5a-dzB1KkmZeWVC2mLcS_PXxYMk" \
    http://localhost:5237/api/Vehicle