curl -i -b ".AspNetCore.Identity.Application=CfDJ8OY5n1bCHihOmEbI-Jaa3nKhtCg-L5L2eODmtI0t1mDtCGZRhWUnEajNS40XUjGaHb27PhX2g851xrK9w00-AHpC-hcXqJJXBV6XcdkeRII13dKdi5G1CfUdno9AtMwLM_HAwloqO8RMzwhWNxPvZAArplgIcLrcRhoL1_ypyMIqlj0JvhvHdaGJIBI7fH2JO98UXzLmNVsxwiJ2ugsT1gtTZfY_IpePE0lJNeCcVPSPLWliCFFnqTZvPIsIhflArqyFyibT149Cx1T3c1GboMPskwRyhFzoDkUapZhz7vXzV0bwU9u73aIAEyrpGz7JsAT_OXzqkWreFcssiml0xf2-ECBOv10AZvT_PqwvMSzZXYks1jq3AmAAsFzl1Ge55-JK-mwL8zqVtXX6DxCX4dn0B3421s3dTG2w44PW0ugVztXlgLCnu8mDFXWpxCEN7HQYOtxf4Lj_KZF-LBFu5M0T3lMSb92Utao6-0LGxbOeOW6hNVKpC2uApNyFdRIvGe-dizRYfJkiwVujZ_OIxYLr_5SGpNLs06iAjFSZmSAHumX9zUaNoLpjadGcqgqqKgk6ZOT9G3RJd4cvr2ociD2dxOoM8d1SlWfmMrB3MAu6P85eFpv6B3OAzXtzXhuFQxrMWgBTC4Uj967kvso8tDKSouOWlaj8MT1sYYlu7ftH9PIETxaDfi3QpIzF_xF0WuUnXjm5jdBk461T9LXYzOA" \
  'http://localhost:5237/api/Enterprise/fc2c4cde-2cc8-4575-b73c-22c60043a0b0' \
  -H 'accept: text/plain'